### PR TITLE
macOS launch and housekeeping scripts

### PR DESCRIPTION
**Pull request by SGDavid**
Submitted in response to https://github.com/Unity-Technologies/unity-cache-server/issues/23

### CODE REVIEW

**Comment by SGDavid** [comment]
Yeah, it's a start; I didn't know how desperate people might be for examples. Regarding parameterization, I can refactor to parameterize at install time, but personally would not be in favor of parameterization at run-time, as it could lead to mischief and confusion about how to put the parameters into effect. The directory structure could also just be a parameter, and then it becomes a local decision.

**Comment by stephen-palmer** [comment]
yes to clarify I meant parameterization at install time, not runtime. And as to directory structure, I was speaking about the `/examples/scripts` path .. I think that should be something different, to at least include the platform name, but not decided exactly what.

**Comment by SGDavid** [comment]
Understood.

**Comment by stephen-palmer** [comment]
I'm going to close this now since it's almost certainly not something we want to officially support, as Asset Database V1 - and by extension, this Cache Server - is nearing end of life.

I would be happy to point to these in the README if they were hosted in a separate repository. Feel free to open a PR to that effect if you want to do so.

**Pull request closed without merging**
